networks:
  proxy-net:
    external: true
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - sonarr-data:/config
      - /opt/docker-data/sonarr/tvseries:/tv #optional
      - /opt/docker-data/sonarr/downloads:/downloads #optional
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    networks:
      - proxy-net
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.home.staniek.name`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls.certresolver: letsencrypt
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
      glance.name: Sonarr
      glance.icon: sh:sonarr
      glance.description: TV Series Manager
      glance.url: https://sonarr.home.staniek.name
      glance.id: sonarr

volumes:
  sonarr-data: