networks:
  proxy-net:
    external: true
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - bazarr-data:/config
      - /opt/docker-data/bazarr/movies:/movies #optional
      - /opt/docker-data/bazarr/tv:/tv #optional
    restart: unless-stopped
    networks:
      - proxy-net
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: Host(`bazarr.home.staniek.name`)
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.tls.certresolver: letsencrypt
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
      glance.name: Bazarr
      glance.icon: sh:bazarr
      glance.description: Media Collection Manager
      glance.url: https://bazarr.home.staniek.name
      glance.id: bazarr

volumes:
  bazarr-data: