global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'amp-terrace'
    static_configs:
      - targets: ['amp-terrace:9100']
  
  - job_name: 'amp-alice'
    static_configs:
      - targets: ['amp-alice:9100']

  - job_name: 'amp-kitchen'
    static_configs:
      - targets: ['amp-kitchen:9100']

  - job_name: 'amp-julia'
    static_configs:
      - targets: ['amp-julia:9100']

  - job_name: 'amp-bathroom'
    static_configs:
      - targets: ['amp-bathroom:9100']
  
  - job_name: 'amp-masterbathroom'
    static_configs:
      - targets: ['amp-masterbathroom:9100']

  - job_name: 'amp-masterbedroom'
    static_configs:
      - targets: ['amp-masterbedroom:9100']
  
  - job_name: 'amp-emily'
    static_configs:
      - targets: ['amp-emily:9100']
  
  - job_name: 'amp-wc'
    static_configs:
      - targets: ['amp-wc:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


rule_files:
  - "/etc/prometheus/alerts.yml"