global:
  resolve_timeout: 5m

route:
  receiver: gotify
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h
  group_by: [ alertname ]

receivers:
  - name: gotify
    webhook_configs:
      - url: 'http://gotify-bridge:8080/gotify_webhook'
        send_resolved: true